version: '3.1'

services:
  wordpress:
    image: wordpress:latest
    container_name: planholmen-wp
    volumes:
        - ./planholmen:/var/www/html/wp-content/themes/planholmen
    ports:
        - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: planholmen
      WORDPRESS_DB_PASSWORD: PLanHolmen
      WORDPRESS_DB_NAME: planholmen

  db:
    image: mysql:5.7
    container_name: planholmen-db
    ports:
    - 3306:3306
    environment:
        MYSQL_DATABASE: planholmen
        MYSQL_USER: planholmen
        MYSQL_PASSWORD: PLanHolmen
        MYSQL_RANDOM_ROOT_PASSWORD: '1'