version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    volumes:
        - ./html:/var/www/html
    ports:
        - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: planholmen
      WORDPRESS_DB_PASSWORD: PLanHolmen
      WORDPRESS_DB_NAME: planholmen

  db:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_DATABASE: planholmen
        MYSQL_USER: planholmen
        MYSQL_PASSWORD: PLanHolmen
        MYSQL_RANDOM_ROOT_PASSWORD: '1'